export const nodes = [
  {
    id: 'process',
    position: { x: -500, y: 550 },
    type: 'customNode',
    data: { input: 'process', bg: '#E79C25' },
  },
  {
    id: 'research',
    position: { x: 0, y: 350 },
    type: 'customNode',
    data: { input: 'research' },
  },
  {
    id: 'planning',
    position: { x: 0, y: 450 },
    type: 'customNode',
    data: { input: 'planning' },
  },
  {
    id: 'designing',
    position: { x: 0, y: 550 },
    type: 'customNode',
    data: { input: 'designing' },
  },
  {
    id: 'designing',
    position: { x: 0, y: 550 },
    type: 'customNode',
    data: { input: 'designing' },
  },
  {
    id: 'manufacturing',
    position: { x: 0, y: 650 },
    type: 'customNode',
    data: { input: 'manufacturing' },
  },
  {
    id: 'sales',
    position: { x: 0, y: 750 },
    type: 'customNode',
    data: { input: 'sales/marketing' },
  },
  {
    id: 'external',
    position: { x: 500, y: 325 },
    type: 'customNode',
    data: { input: 'external' },
  },
  {
    id: 'external',
    position: { x: 500, y: 325 },
    type: 'customNode',
    data: { input: 'external' },
  },
  {
    id: 'internal',
    position: { x: 500, y: 425 },
    type: 'customNode',
    data: { input: 'internal' },
  },
  {
    id: 'prd',
    position: { x: 500, y: 525 },
    type: 'customNode',
    data: { input: 'prd' },
  },
  {
    id: 'specs',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'specs' },
  },
  {
    id: 'hardware',
    position: { x: 500, y: 525 },
    type: 'customNode',
    data: { input: 'hardware' },
  },
  {
    id: 'software',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'software' },
  },
  {
    id: 'material',
    position: { x: 500, y: 525 },
    type: 'customNode',
    data: { input: 'material' },
  },
  {
    id: 'production',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'production' },
  },
  {
    id: 'online',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'online' },
  },
  {
    id: 'dealership',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'dealership' },
  },
  {
    id: 'B2C1',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'B2C' },
  },
  {
    id: 'B2C2',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'B2C' },
  },
  {
    id: 'online_',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'Online' },
  },
  {
    id: 'interview',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'interview' },
  },
  {
    id: 'publicdata',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'public data' },
  },
  {
    id: 'health',
    position: { x: 500, y: 625 },
    type: 'customNode',
    data: { input: 'health' },
  },
];
