export const nodes = [
  {
    id: 'process',
    position: { x: 105, y: 675 },
    type: 'customNode',
    data: { input: 'process', bg: '#E79C25' },
  },
  {
    id: 'research',
    position: { x: 515, y: 275 },
    type: 'customNode',
    data: { input: 'research', bg: '#2F4858' },
  },
  {
    id: 'planning',
    position: { x: 515, y: 475 },
    type: 'customNode',
    data: { input: 'planning', bg: '#00626E' },
  },
  {
    id: 'designing',
    position: { x: 515, y: 675 },
    type: 'customNode',
    data: { input: 'designing', bg: '#2F4858' },
  },
  {
    id: 'manufacturing',
    position: { x: 515, y: 875 },
    type: 'customNode',
    data: { input: 'manufacturing', bg: '#00626E' },
  },
  {
    id: 'sales',
    position: { x: 515, y: 1075 },
    type: 'customNode',
    data: { input: 'sales/marketing', bg: '#2F4858' },
  },
  {
    id: 'external',
    position: { x: 925, y: 175 },
    type: 'customNode',
    data: { input: 'external', bg: '#919D29' },
  },
  {
    id: 'internal',
    position: { x: 925, y: 275 },
    type: 'customNode',
    data: { input: 'internal', bg: '#43904F' },
  },
  {
    id: 'prd',
    position: { x: 925, y: 375 },
    type: 'customNode',
    data: { input: 'prd', bg: '#919D29' },
  },
  {
    id: 'specs',
    position: { x: 925, y: 475 },
    type: 'customNode',
    data: { input: 'specs', bg: '#43904F' },
  },
  {
    id: 'hardware',
    position: { x: 925, y: 575 },
    type: 'customNode',
    data: { input: 'hardware', bg: '#919D29' },
  },
  {
    id: 'software',
    position: { x: 925, y: 675 },
    type: 'customNode',
    data: { input: 'software', bg: '#43904F' },
  },
  {
    id: 'material',
    position: { x: 925, y: 775 },
    type: 'customNode',
    data: { input: 'material', bg: '#919D29' },
  },
  {
    id: 'production',
    position: { x: 925, y: 875 },
    type: 'customNode',
    data: { input: 'production', bg: '#43904F' },
  },
  {
    id: 'online',
    position: { x: 925, y: 975 },
    type: 'customNode',
    data: { input: 'online', bg: '#919D29' },
  },
  {
    id: 'dealership',
    position: { x: 925, y: 1075 },
    type: 'customNode',
    data: { input: 'dealership', bg: '#43904F' },
  },
  {
    id: 'B2C1',
    position: { x: 1335, y: 125 },
    type: 'customNode',
    data: { input: 'B2C', bg: '#AE9C06' },
  },
  {
    id: 'B2C2',
    position: { x: 1335, y: 225 },
    type: 'customNode',
    data: { input: 'B2C', bg: '#43904F' },
  },
  {
    id: 'online_',
    position: { x: 1745, y: 25 },
    type: 'customNode',
    data: { input: 'Online', bg: '#007261' },
  },
  {
    id: 'interview',
    position: { x: 1745, y: 125 },
    type: 'customNode',
    data: { input: 'interview', bg: '#00814B' },
  },
  {
    id: 'publicdata',
    position: { x: 1745, y: 225 },
    type: 'customNode',
    data: { input: 'public data', bg: '#318E32' },
  },
  {
    id: 'health',
    position: { x: 1745, y: 325 },
    type: 'customNode',
    data: { input: 'health', bg: '#749717' },
  },
];
